// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvgLxFmaiH5elPgP3aW44XyhI0qgGhKpc',
    appId: '1:827588430487:web:3a85e665380abacca6b7d2',
    messagingSenderId: '827588430487',
    projectId: 'travel-72b48',
    authDomain: 'travel-72b48.firebaseapp.com',
    storageBucket: 'travel-72b48.firebasestorage.app',
    measurementId: 'G-N47H9QSG2Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGFu6r7T2iJsbdJIsw8yK1aGkk3iTIGNw',
    appId: '1:827588430487:android:4d4c52f9b749bcaca6b7d2',
    messagingSenderId: '827588430487',
    projectId: 'travel-72b48',
    storageBucket: 'travel-72b48.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBByz5oClRyW0jRCvm0I139gnGKfr-uw-k',
    appId: '1:827588430487:ios:418dff040cec7122a6b7d2',
    messagingSenderId: '827588430487',
    projectId: 'travel-72b48',
    storageBucket: 'travel-72b48.firebasestorage.app',
    iosBundleId: 'com.example.practical1',
  );
}
